// Fill out your copyright notice in the Description page of Project Settings.


#include "Combat/LockonComponent.h"
#include "GameFramework/Character.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "GameFramework/SpringArmComponent.h"
#include "Kismet/KismetMathLibrary.h"

// Sets default values for this component's properties
ULockonComponent::ULockonComponent()
{
	// Set this component to be initialized when the game starts, and to be ticked every frame.  You can turn these features
	// off to improve performance if you don't need them.
	PrimaryComponentTick.bCanEverTick = true;

	// ...
} 

// Called when the game starts
void ULockonComponent::BeginPlay()
{
	Super::BeginPlay();

	OwnerRef = GetOwner<ACharacter>();
	Controller = GetWorld()->GetFirstPlayerController();
	MovementComp = OwnerRef->GetCharacterMovement();
	SpringArmComp = OwnerRef->FindComponentByClass<USpringArmComponent>();
	
}

void ULockonComponent::StartLockon(float Radius)
{
	FHitResult OutResult;
	FVector CurrentLocation{ OwnerRef->GetActorLocation() };
	FCollisionShape	Sphere{ FCollisionShape::MakeSphere(Radius)};
	FCollisionQueryParams IgnoreParams{
		FName{ TEXT("Ignore Collision Params") },
		false,
		OwnerRef	
	};
	bool bHasFoundTarget{ GetWorld()->SweepSingleByChannel(
		OutResult,
		CurrentLocation,
		CurrentLocation,
		FQuat::Identity, //used when don't care about the rotation; essentially says there isn't one --bhd
		ECollisionChannel::ECC_GameTraceChannel1,
		Sphere,
		IgnoreParams
	) };


	if (!bHasFoundTarget) { return; }

	CurrentTargetActor = OutResult.GetActor();
	Controller->SetIgnoreLookInput(true);
	MovementComp->bOrientRotationToMovement = false;
	MovementComp->bUseControllerDesiredRotation = true;

	SpringArmComp->TargetOffset = FVector{ 0.0, 0.0, 100.0};
	

	// UE_LOG(
	// 	LogTemp, Warning, TEXT("Actor Detected: %s"),
	// 	*OutResult.GetActor()->GetName()
	// );
}

void ULockonComponent::EndLockon()
{
	CurrentTargetActor = nullptr;
	MovementComp->bOrientRotationToMovement = true;
	MovementComp->bUseControllerDesiredRotation = false;
	SpringArmComp->TargetOffset = FVector::ZeroVector;
	Controller->ResetIgnoreLookInput();
}

void ULockonComponent::ToggleLockon(float Radius)
{
	if (IsValid(CurrentTargetActor))
	{
		EndLockon();	
	}
	else
	{
		StartLockon();
	}
}


// Called every frame
void ULockonComponent::TickComponent(
	float DeltaTime,
	ELevelTick TickType,
	FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

	if (!IsValid(CurrentTargetActor)) { return; }

	FVector CurrentOwnerLocation = { OwnerRef->GetActorLocation() };
	FVector CurrentTargetActorLocation = { CurrentTargetActor->GetActorLocation() };

	UE_LOG(
		LogTemp, Warning, TEXT("CurrentTargetActor Location: %s"),
		*CurrentTargetActor->GetActorLocation().ToString()
	);

	CurrentTargetActorLocation.Z -= 125;

	FRotator NewRotation { UKismetMathLibrary::FindLookAtRotation(
		CurrentOwnerLocation,
		 CurrentTargetActorLocation
	)};

	Controller->SetControlRotation(NewRotation);
		
}

